import { createApp } from "vue";
import NavbarComponent from "./components/Navbar.vue";
import HeroComponent from "./components/Hero.vue";
import PermasalahanSection from "./components/PermasalahanSection.vue";
import RocketStoveSection from "./components/RocketStoveSection.vue";
import DampakSection from "./components/DampakSection.vue";
import CtaSection from "./components/CtaSection.vue";
import FooterComponent from "./components/Footer.vue";
import TentangHeroComponent from "./components/TentangHero.vue";
import LatarBelakangSection from "./components/LatarBelakangSection.vue";
import MengapaSection from "./components/MengapaSection.vue";
import ProgramSection from "./components/ProgramSection.vue";
import TimSection from "./components/TimSection.vue";
import MitraProgramSection from "./components/MitraProgramSection.vue";
import RocketStoveHero from "./components/RocketStoveHero.vue";
import MengenalRocketStoveSection from "./components/MengenalRocketStoveSection.vue";
import StrukturRocketStoveSection from "./components/StrukturRocketStoveSection.vue";
import CaraKerjaRocketStoveSection from "./components/CaraKerjaRocketStoveSection.vue";
import AlurPembakaranSection from "./components/AlurPembakaranSection.vue";
import EdukasiHeroSection from "./components/EdukasiHeroSection.vue";
import EdukasiSederhanaSection from "./components/EdukasiSederhanaSection.vue";
import EdukasiJenisSampahSection from "./components/EdukasiJenisSampahSection.vue";
import EdukasiAlasanPilahSection from "./components/EdukasiAlasanPilahSection.vue";
import EdukasiDampakPembakaranSection from "./components/EdukasiDampakPembakaranSection.vue";
import EdukasiKebiasaanBaikSection from "./components/EdukasiKebiasaanBaikSection.vue";
import EdukasiBersamaSection from "./components/EdukasiBersamaSection.vue";
import EdukasiCtaSection from "./components/EdukasiCtaSection.vue";
import DokumentasiHeroSection from "./components/DokumentasiHeroSection.vue";
import DokumentasiGridSection from "./components/DokumentasiGridSection.vue";
import DokumentasiTerimaKasihSection from "./components/DokumentasiTerimaKasihSection.vue";
import CaraPenggunaanSection from "./components/CaraPenggunaanSection.vue";
import TipsPenggunaanSection from "./components/TipsPenggunaanSection.vue";
import RocketStoveCtaSection from "./components/RocketStoveCtaSection.vue";

const app = createApp({});

app.component("navbar-component", NavbarComponent);
app.component("hero-component", HeroComponent);
app.component("permasalahan-section", PermasalahanSection);
app.component("rocket-stove-section", RocketStoveSection);
app.component("dampak-section", DampakSection);
app.component("cta-section", CtaSection);
app.component("footer-component", FooterComponent);
app.component("tentang-hero-component", TentangHeroComponent);
app.component("latar-belakang-section", LatarBelakangSection);
app.component("mengapa-section", MengapaSection);
app.component("program-section", ProgramSection);
app.component("tim-section", TimSection);
app.component("mitra-program-section", MitraProgramSection);
app.component("rocket-stove-hero", RocketStoveHero);
app.component("mengenal-rocket-stove-section", MengenalRocketStoveSection);
app.component("struktur-rocket-stove-section", StrukturRocketStoveSection);
app.component("cara-kerja-rocket-stove-section", CaraKerjaRocketStoveSection);
app.component("alur-pembakaran-section", AlurPembakaranSection);
app.component("edukasi-hero-section", EdukasiHeroSection);
app.component("edukasi-sederhana-section", EdukasiSederhanaSection);
app.component("edukasi-jenis-sampah-section", EdukasiJenisSampahSection);
app.component("edukasi-alasan-pilah-section", EdukasiAlasanPilahSection);
app.component("edukasi-dampak-pembakaran-section", EdukasiDampakPembakaranSection);
app.component("edukasi-kebiasaan-baik-section", EdukasiKebiasaanBaikSection);
app.component("edukasi-bersama-section", EdukasiBersamaSection);
app.component("edukasi-cta-section", EdukasiCtaSection);
app.component("dokumentasi-hero-section", DokumentasiHeroSection);
app.component("dokumentasi-grid-section", DokumentasiGridSection);
app.component("dokumentasi-terima-kasih-section", DokumentasiTerimaKasihSection);
app.component("cara-penggunaan-section", CaraPenggunaanSection);
app.component("tips-penggunaan-section", TipsPenggunaanSection);
app.component("rocket-stove-cta-section", RocketStoveCtaSection);

app.mount("#app");
